aszlig/lazy-packages: Replace mpg321 by mpg123
I could probably even delete that package since I'm not using it, but to
get evaluation fixed, let's just use the suggestion right now from the
eval error:

  error: 'mpg321' has been removed due to it being unmaintained by
  upstream. Consider using mpg123 instead.

Signed-off-by: aszlig <aszlig@nix.build>