games/monogame-patcher: Fix evaluation
The evaluation error is:

  error: function 'anonymous lambda' called without required argument 'pname'

This is because the "baseName" attributes of the dotnet tooling have
changed to the more common "pname" attributes that we use throughout
nixpkgs.

Signed-off-by: aszlig <aszlig@nix.build>