profile: Use nixVersions.latest by default
Another eval error to fix:

  error: nixVersions.unstable has been removed. For bleeding edge (Nix
  master, roughly weekly updated) use nixVersions.git, otherwise use
  nixVersions.latest.

I do track Git versions, but in this case it's for the base Nix version
I want to use on all my machines, so let's stick to the latest release
version since we can still use newer versions on an ad-hoc basis.

Signed-off-by: aszlig <aszlig@nix.build>