machines/tyree: Fix evaluation of weboob
One (or maybe more?) dependency of weboob requires Python 3 and hence
using weboob from python2Packages isn't going to evaluate and instead
result in this error:

  error: google-api-core-1.16.0 not supported for interpreter python2.7

Using weboob from python3Packages fixes the eval error.

Signed-off-by: aszlig <aszlig@nix.build>