core/tests: Fix evaluation errors
The simplest one to fix is the "morty" test because:

  error: The option `services.morty' can no longer be used since it's
  been removed. services.morty has been removed from NixOS. As the morty
  package was unmaintained and removed and searxng, its main consumer,
  dropped support for it.

The PostgreSQL extensions are now implemented as a package scope, so we
get an eval error like this:

  error: expected a list but found a set: { __functionArgs = «thunk»;
  __functor = «thunk»; }

I fixed both the pgjwt and postgis tests accordingly.

Signed-off-by: aszlig <aszlig@nix.build>