firefox: Fix evaluation of override arguments
Evaluation fails with:

  error: function 'anonymous lambda' called with unexpected argument
  'requireSigning'

This is because a recent change[1] cleaned up the arguments a little bit
so that it conforms to RFC169[2]. In our case this also has the
advantage, that we now no longer need to override buildMozillaMach in
order to disable addon signing and allowing sideloading.

[1]: https://github.com/NixOS/nixpkgs/commit/cf6a014d171b2eccc2efc2587ac
[2]: https://github.com/NixOS/rfcs/pull/169

Signed-off-by: aszlig <aszlig@nix.build>