core: Remove test for removed dhparams module
Fixes the following eval error:

  error: The option `security.dhparams' can no longer be used since it's
  been removed. The security.dhparams module has been removed as RFC
  7919 has shown that generating your own params is problematic.

Signed-off-by: aszlig <aszlig@nix.build>