gnupg: Switch to pinentry-qt by default
The module fails to evaluate with:

  error: 'pinentry-gtk2' has been removed as it depended on the
  deprecated GTK2 engine, use pinentry-gnome3 instead.

I'm using pinentry-qt instead of pinentry-gnome3, because on my system
using the gnome3 variant falls back to using TTY and I don't have time
debugging this at the moment.

Signed-off-by: aszlig <aszlig@nix.build>