machines/labtop: Fix syntax error
Regression introduced by d99fd1ba860dd513508a7460bf139e9ee990a5d3.

Fixes the following evaluation error:

error: syntax error, unexpected '}', expecting ';', at labtop.nix:110:55

Signed-off-by: aszlig <aszlig@redmoonstudios.org>