vim: Switch to buildGoModule for hexokinase
This fixes the following evaluation error:

  error: `buildGoPackage` has been deprecated and removed, see the Go
  section in the nixpkgs manual for details

I've built Vim and checked to see whether it's still displaying colours
as intended and they do.

Signed-off-by: aszlig <aszlig@nix.build>