core/tests: Fix checks for krb5 tests
This fixes the following evaluation error:

  error: The option `krb5.kerberos' can no longer be used since it's
  been removed. The option `krb5.kerberos' has been moved to
  `security.krb5.package'.

Signed-off-by: aszlig <aszlig@nix.build>