psi: Update to latest master
This is mainly because of the following build failure that seems to have
been fixed upstream:

  widgets/emojiregistry.cpp: In member function 'EmojiRegistry::Category EmojiRegistry::startCategory(QStringRef) const':
  widgets/emojiregistry.cpp:40:10: error: 'uint32_t' is not a member of 'std'; did you mean 'wint_t'?
     40 |     std::uint32_t ucs;
        |          ^~~~~~~~
        |          wint_t
  widgets/emojiregistry.cpp:44:9: error: 'ucs' was not declared in this scope
     44 |         ucs = QChar::surrogateToUcs4(in[0], in[1]);
        |         ^~~
  widgets/emojiregistry.cpp:46:9: error: 'ucs' was not declared in this scope
     46 |         ucs = in[0].unicode();
        |         ^~~
  widgets/emojiregistry.cpp:51:9: error: 'ucs' was not declared in this scope
     51 |     if (ucs == 0x200d)
        |         ^~~
  widgets/emojiregistry.cpp:53:9: error: 'ucs' was not declared in this scope
     53 |     if (ucs == 0xfe0f)
        |         ^~~
  widgets/emojiregistry.cpp:55:9: error: 'ucs' was not declared in this scope
     55 |     if (ucs <= 0x39 && in.length() > 2 && (ucs >= 0x30 || ucs == 0x2a || ucs == 0x23) && in[1].unicode() == 0xfe0f
        |         ^~~
  widgets/emojiregistry.cpp:61:38: error: 'ucs' was not declared in this scope
     61 |     auto lb    = ranges_.lower_bound(ucs);
        |                                      ^~~

Of course, the second reason is that the current version seems to be way
too stable and I want to have a fresh round of new bugs.

Signed-off-by: aszlig <aszlig@nix.build>