command-not-found: Add workaround for eval error
The upstream module enables this with mkDefault if the
programs.command-not-found.dbPath setting contains an existing path,
which then would not conflict with our definition.

However we still get the following eval error:

  error: The option `programs.command-not-found.enable' has conflicting definition values:
  - In `/nix/store/060yvsh5s6mw6ypwh0ckg46nc7p2m549-vuizvui-pre4457.a6c2b52d/modules/core/common.nix': true
  - In `/nix/store/75bkaivfbwq3x8cs7155hag7hs1chjcx-source/nixos/modules/programs/command-not-found/command-not-found.nix': false
  Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.

... which would indicate that builtins.pathExists evaluates to false for
some reason for our definition for dbPath.

Since this currently breaks eval for all machines, I decided to give our
definition a priority of 990 so that it still more or less boils down to
"true being default", since my guess is that most overrides of this
option would be much lower than 990 or even 900.

We still need to figure out though why we run into that conflict, but to
get stuff to evaluate I used priority 990 as a temporary compromise.

Signed-off-by: aszlig <aszlig@nix.build>
Cc: @sternenseemann