core/tests: Fix eval error due to mxisd removal
Fixes the following eval error:

  error: The option `services.mxisd' can no longer be used since it's
  been removed. The mxisd module has been removed as both mxisd and
  ma1sd got removed.

Signed-off-by: aszlig <aszlig@nix.build>