call-machine: Fix eval for ISO images
Since quite a while we have eval errors like this:

  error: A definition for option `boot.loader.grub.enable' is not of type `boolean'. Definition values:
  - In `/nix/store/pwz215rbi41pq6dwrj4s7s7whf9hjq4s-vuizvui-pre4496.d7cf0d3c/lib/call-machine.nix':
      {
        _type = "override";
        content = false;
        priority = 60;
      }

This is because we evaluate the relevant modules without using the
NixOS module system first und use the values of those relevant modules
with a mkForce (which is an alias for mkOverride).

The problem with this is that we can't nest definitions of mkOverride
like this and we can only use plain values here.

Note that the reason why we don't go via the NixOS module system is
because the resulting values are not only the definitions from the
*target* module but *all* modules combined.

To address this for now, we now just replace all the overrides given to
mkForce by their respective contents. I haven't tested whether the
resulting ISO images actually work, but at least they should evaluate
again.

Signed-off-by: aszlig <aszlig@nix.build>