pkgs/aacolorize: Fix eval error
Python packages now require to specify the build method:

  error: python3.13-aacolorize does not configure a `format`. To build
  with setuptools as before, set `pyproject = true` and `build-system =
  [ setuptools ]`.

Since the package in question is ancient, let's just go for setuptools
for now to get rid of the eval error.

Signed-off-by: aszlig <aszlig@nix.build>